# Generated by Django 5.2 on 2026-08-15 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('hotel', 'Hotel'), ('pg', 'PG'), ('hostel', 'Hostel'), ('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('local_essential', 'Local Essential')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('price_range', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('internal', 'Internal Database'), ('external_places_api', 'External Places API'), ('admin_entered', 'Admin Entered')], default='admin_entered', max_length=50)),
                ('verified', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('amenities', models.JSONField(blank=True, null=True)),
                ('opening_hours', models.JSONField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('attributes', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category', 'verified'], name='places_plac_categor_d595f3_idx')],
            },
        ),
    ]
